version: "3.7"
services:
  web1:
    build: ./quote_gen
    deploy:
      replicas: 2
    restart: always
    ports:
      - "6001-6002:5000"
    volumes:
      - ./quote_gen:/app
  web2:
    build: ./quote_disp
    deploy:
      replicas: 2
    restart: always
    ports:
      - "5001-5002:5001"
    volumes:
      - ./quote_disp:/app
    depends_on:
      - web1
